name: alpaca 7B
on:
  schedule:
    - cron: "10 * * * *"
jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: alpaca
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: 'https://us-central1-arched-keyword-306918.cloudfunctions.net/run-inference-1'
          method: 'POST'
          customHeaders: '{"User-Agent": "Mozilla/5.0 (Linux; Android 7.0; S51) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36"}'
          data: '{"prompt": "hi!"}'
      - name: output
        run: |
          if echo "${{ steps.alpaca.outputs.response }}" | grep -q "completion"; then
            echo "ONLINE"
          else
            echo "OFFLINE"
          fi
