name: API monitoring
on:
  schedule:
    - cron: "10 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      steps:
        - uses: actions/checkout@v3
        - name: usage python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
          - name: installation of additional packages/libraries.
            run: |
              python -m pip install --upgrade pip
              pip install git+https://github.com/HotDrify/freeAI
          - name: result
            run: |
              python tests.py
        