name: Status Page

on: [push]

jobs:

  send-requests:

    runs-on: ubuntu-latest

    steps:

      - name: Send POST requests

        run: |

          curl -X POST https://example.com/api \

          -H 'Content-Type: application/json' \

          -d '{"key": "value"}' &

          curl -X POST https://example.ru/api \

          -H 'Content-Type: application/json' \

          -d '{"key": "value"}' &

          curl -X POST https://example.ml/api \

          -H 'Content-Type: application/json' \

          -d '{"key": "value"}' &

        wait

      - name: check

        run: |

          if [[ $(curl -s https://example.com/api | jq -r '.content') == "null" ]]; then

            echo "OFFLINE"

          else

            echo "ONLINE"

          fi

          

          if [[ $(curl -s https://example.ru/api | jq -r '.content') == "null" ]]; then

            echo "OFFLINE"

          else

            echo "ONLINE"

          fi

          

          if [[ $(curl -s https://example.ml/api | jq -r '.content') == "null" ]]; then

            echo "OFFLINE"

          else

            echo "ONLINE"

          fi
