name: API monitoring
on:
  schedule:
    - cron: "10 * * * *"
jobs:
  avagpt:
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: avagpt
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: 'https://ava-alpha-api.codelink.io/api/chat'
          method: 'POST'
          customHeaders: '{"User-Agent": "Mozilla/5.0 (Linux; Android 7.0; S51) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36", "accept": "application/json"}'
          json: '{"model": "gpt-4", "temperature": 0.5, "stream": true, "messages": [{"role": "user", "content": "hi"}]}'
      - name:
        run: |
          if echo "${{ steps.avagpt.outputs.response }}" | grep -q "completion"; then
            echo "avaGPT: ONLINE"
          else
            echo "avaGPT: OFFLINE"
          fi
  alpaca:
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: alpaca
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: 'https://us-central1-arched-keyword-306918.cloudfunctions.net/run-inference-1'
          method: 'POST'
          customHeaders: '{"User-Agent": "Mozilla/5.0 (Linux; Android 7.0; S51) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36"}'
          data: '{"prompt": "hi!"}'
      - name: alpaca-get
        run: |
          if echo "${{ steps.alpaca.outputs.response }}" | grep -q "completion"; then
            echo "alpaca-7B: ONLINE"
          else
            echo "alpaca-7B: OFFLINE"
          fi
